name: dictionary_app
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter  
  cupertino_icons: ^1.0.2
  http: ^1.1.2
  get_it: ^7.6.4
  shared_preferences: ^2.2.2
  flutter_bloc: ^8.1.3
  sqflite: ^2.3.0
  flutter_tts: ^3.8.5
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:  
  uses-material-design: true
  assets:
    - assets/words_dictionary.json

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
